#!/usr/bin/env bash

# Script to get the plugin version.

# Set the SOURCE_PATH variable to the current directory or use the passed argument.
SOURCE_PATH=${1:-$(pwd)}
PLUGIN_SLUG=$(pslug ${SOURCE_PATH})
PLUGIN_FILE_PATH="${SOURCE_PATH}/${PLUGIN_SLUG}.php"

# Show the usage information.
usage() {
    echo "Usage: pversion [source_path]"
    echo ""
    echo "source_path: The path to the source code of the plugin."
    echo "             Default: The current directory."
}

# Check if the usage information should be displayed.
if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    usage
    exit 0
fi

# Check if the main plugin file exists in the source path.
if [ ! -f "${PLUGIN_FILE_PATH}" ]; then
    echo "The main plugin file does not exist in the source path."
    echo ""
    echo "Source path: ${SOURCE_PATH}"
    exit 1
fi

# Get the plugin version from the main plugin file.
cat $PLUGIN_FILE_PATH | grep "* Version:" | sed 's/ //g' | awk -F: '{print $NF}'
