#!/usr/bin/env bash

# Script to display horizontal separator line
# Requires: repeat in PATH and cols variable

show_help() {
    echo "Usage: echo-separator"
    echo ""
    echo "Example:"
    echo "echo-separator"
    echo ""
}

cols=$(terminal-cols)

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    show_help
    exit 0
fi

echo ""
repeat "-" "${cols}"
echo ""
echo ""
